		SELECT * FROM PRECOS WHERE PC_DESCRICAO LIKE '%tuss,%'

		--75 CIEFAS
UPDATE PRECOS_PORTE_CBHPM 
SET 
	CB_VALOR=CONVERT (DECIMAL (15,2),(CB_VALOR*1.1017)), 
	CB_CUSTO_OPER= CONVERT (DECIMAL(15,2),(CB_CUSTO_OPER*1.0406))
FROM PRECOS_PORTE_CBHPM WHERE CB_PRECO=249

--

SELECT PR_PRODUTO, PR_DESCRICAO,CONVERT (DECIMAL (12,2),(((CB_VALOR*QT_CBHPM_PERC)*CB_BANDA_EXM)+(CB_CUSTO_OPER*QT_CBHPM_CUSTO))), CB_VALOR, QT_CBHPM_PORTE, QT_CBHPM_PERC, QT_CBHPM_CUSTO , * 
FROM QUANTIDADE_COEFICIENTE
	INNER JOIN PRECOS_PORTE_CBHPM ON QT_PRECO=PRECOS_PORTE_CBHPM.CB_PRECO AND QT_CBHPM_PORTE=CB_PORTE
	INNER JOIN PRODUTOS ON PR_ID=QT_PRODUTO
WHERE QT_PRECO=274

BEGIN TRAN
UPDATE 
	QUANTIDADE_COEFICIENTE 
SET 
	QT_QUANTIDADE_INDICE= CONVERT (DECIMAL (12,2),(((CB_VALOR*ISNULL (QT_CBHPM_PERC,1))*CB_BANDA_EXM)+(CB_CUSTO_OPER* ISNULL (QT_CBHPM_CUSTO,0))))
	,ALTERACAO=GETDATE (), OPERADOR='VICTOR GIFFONI'
--SELECT PR_PRODUTO, CONVERT (DECIMAL (12,2),(((CB_VALOR*ISNULL (QT_CBHPM_PERC,1))*CB_BANDA_EXM)+(CB_CUSTO_OPER* ISNULL (QT_CBHPM_CUSTO,0)))), QT_QUANTIDADE_INDICE, QT_CBHPM_CUSTO, CB_VALOR, QT_CBHPM_PERC
FROM 
	QUANTIDADE_COEFICIENTE
		INNER JOIN PRECOS_PORTE_CBHPM ON QT_PRECO=PRECOS_PORTE_CBHPM.CB_PRECO AND QT_CBHPM_PORTE=CB_PORTE
		INNER JOIN PRODUTOS ON PR_ID=QT_PRODUTO
WHERE QT_PRECO=271 AND QT_QUANTIDADE_INDICE<>(CONVERT (DECIMAL (12,2),(((CB_VALOR*ISNULL (QT_CBHPM_PERC,1))*CB_BANDA_EXM)+(CB_CUSTO_OPER* ISNULL (QT_CBHPM_CUSTO,0)))))
ROLLBACK

UPDATE QUANTIDADE_COEFICIENTE SET QT_CBHPM_CUSTO=0 WHERE QT_CBHPM_CUSTO IS NULL


BEGIN TRAN
UPDATE QUANTIDADE_COEFICIENTE SET QT_CBHPM_PORTE='9A'
FROM PRODUTOS INNER JOIN QUANTIDADE_COEFICIENTE ON QT_PRODUTO=PR_ID
WHERE PR_PRODUTO='31005446' --AND QT_CBHPM_PORTE IS NULL
ROLLBACK

SELECT PR_PRODUTO, PR_DESCRICAO,QT_CBHPM_PORTE, * 
FROM QUANTIDADE_COEFICIENTE 
INNER JOIN PRODUTOS ON QT_PRODUTO=PR_ID
WHERE QT_PRECO=280 AND NOT EXISTS (SELECT * FROM PRECOS_PORTE_CBHPM WHERE CB_PRECO=280 AND CB_PORTE=QT_CBHPM_PORTE)

SELECT CONVERT (DECIMAL (15,2),(CB_VALOR*1.1017)), CB_VALOR, CONVERT (DECIMAL(15,2),(CB_CUSTO_OPER*1.0406 )), CB_CUSTO_OPER
FROM PRECOS_PORTE_CBHPM WHERE PRECOS_PORTE_CBHPM.CB_PRECO=249

UPDATE PRECOS_PORTE_CBHPM 
SET 
	CB_VALOR=CONVERT (DECIMAL (15,2),(CB_VALOR*1.1017)), 
	CB_CUSTO_OPER= CONVERT (DECIMAL(15,2),(CB_CUSTO_OPER*1.0406))
FROM PRECOS_PORTE_CBHPM WHERE PRECOS_PORTE_CBHPM.CB_PRECO=249


SELECT * FROM QUANTIDADE_COEFICIENTE WHERE QT_CBHPM_CUSTO IS NULL AND QT_PRECO=264


UPDATE QUANTIDADE_COEFICIENTE SET QT_CBHPM_CUSTO=0  WHERE QT_CBHPM_CUSTO IS NULL AND QT_PRECO=249